import Head from "next/head";
import About from "../components/About/About";
import Apartments from "../components/Apartments/Apartments";
import Cart from "../components/Cart/Cart";
import MainHead from "../components/MainHead/MainHead";
import PriceRoom from "../components/PriceRoom/PriceRoom";
import Realters from "../components/Realters/Realters";
import Services from "../components/Services/Services";
import styles from "../styles/Home.module.sass";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Главная</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainHead />
      <Cart />
      <About />
      <Services />
      <Apartments />
      <PriceRoom />
      <Realters />
    </div>
  );
}
